workflows:
  android-apk-workflow:
    name: Build Android APK

    environment:
      flutter: stable # Pastikan versi Flutter yang diinginkan

    scripts:
      - name: Install Dependencies
        script: flutter pub get

      - name: Generate Dependency Injection Files
        script: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
